spring:
  application:
    name: zuul

zuul:
  routes:
    location:
      path: /**
    skill:
      path: /**
    user:
      path: /**
    batch:
      path: /**

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOME}

server:
  port: 9090