spring:
  application:
    name: zuul
zuul:
  routes:
    location:
      path: /**/location/**
    skill:
      path: /**/skill/**
    user:
      path: /**/trainee/**
    batch:
      path: /**/batch/**
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOME}
server:
  port: 9090