spring:
  application:
    name: zuul

zuul:
  routes:
    quality-audit:
      path: /qa/**
      service-id: quality-audit-service
    user:
      path: /user/**
      service-id: user-service
    batch:
      path: /batch/**
      service-id: batch-service
    assessment:
      path: /assessment/**
      service-id: assessment-service
    location:
      path: /location/**
      service-id: location-service
    category:
      path: /category/**
      service-id: category-service
    skilltype:
      path: /skill/**
      service-id: skilltype-service
eureka:
  client:
    service-url:
      default-zone: http://54.147.136.238:32861/ 

server:
  port: 10000