spring:
  application:
    name: zuul

zuul:
  ignored-services: '*'  # Don't allow access to route by serviceId
                         # i.e. http://location-service/location/all/location/all wont work
                         # i.e. http://localhost:10000/location/all/location/all will work
  routes:
    quality-audit-service:
      path: /qa/**
      service-id: quality-audit-service
      strip-prefix: false
    user-service:
      path: /user/**
      service-id: user-service
      strip-prefix: false
    batch-service:
      path: /batch/**
      service-id: batch-service
      strip-prefix: false
    assessment-service:
      path: /assessment/**
      service-id: assessment-service
      strip-prefix: false
    location-service:
      path: /location/**
      service-id: location-service
      strip-prefix: false
    category-service:
      path: /category/**
      service-id: category-service
      strip-prefix: false
    skilltype-service:
      path: /skill/**
      service-id: skilltype-service
      strip-prefix: false
  ribbon:
    eager-load:
      enabled: true # Don't wait to load route
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 10000


# Increase timeout on reads to be 15000 ms instead of default 2000 ms
ribbon:
  ReadTimeout: 15000
management:
  endpoint:
    web:
      exposure:
        include: '*'